improves the performance of download_orbit for GipsyX processing

diff --git a/CODE/shells/gnss_run_gipsyx b/CODE/shells/gnss_run_gipsyx
--- a/CODE/shells/gnss_run_gipsyx
+++ b/CODE/shells/gnss_run_gipsyx
@@ -11,13 +11,13 @@
 #		      FID_RECEIVER: receiver code name (overwrites Rinex header)
 #		       FID_ANTENNA: antenna code name (overwrites Rinex header)
 #
-# 
+#
 # Authors: François BEAUDUCEL, Edgar LENHOF, Patrice BOISSIER
-#          
+#
 # Created: 2019-02-11 at PVMBG, Bandung (Indonesia)
 #          Based on Gipsy-Oasis version by Francois BEAUDUCEL (IPGP) and Ahmad Ali FAHMI (IRD),
 #          Domerapi/WebObs Project, 2014.
-# Updated: 2019-10-03
+# Updated: 2020-08-07
 
 #Check lock file
 LOCKFILE=/tmp/gnss_run_gipsyx.txt
@@ -26,27 +26,29 @@ if [ -e ${LOCKFILE} ] && kill -0 `cat ${LOCKFILE}`; then
 	exit
 fi
 
-# Helper 
+# Helper
 if [ $# -lt 2 ]; then
-	echo " Syntax: gnss_run_gipsyx CONF DAYS [STATION] [-s \"STALIST\"] [-d yyyy/mm/dd,yyyy/mm/dd] [-force] [-lock]"
+	echo "      Syntax: gnss_run_gipsyx CONF DAYS [options]"
 	echo " Description: runs the automatic GNSS process from raw files to position solution"
-	echo "    Arguments:"
+	echo "   Arguments:"
 	echo "       CONF = configuration filename, e.g., /etc/webobs.d/gnss_run_gipsyx.rc"
 	echo "       DAYS = number of days to process (from today)"
-	echo "    Optionnal arguments:"
-	echo "	     -s \"STA1 STA2...\""
-	echo "          station code or station list with double quotes"
-	echo "	        default is all nodes associated with local WebObs $GRID"
-	echo "          or a list of nodes $NODES defined in .rc"
-	echo "       -d yyyy/mm/dd,yyyy/mm/dd"
-	echo "          choose days to start process; the DAYS argument can still be used to"
-	echo "          process previous days from the selected ones, for instance:"
-	echo "             gnss_run_gipsyx CONF 1 -d 2017/03/17,2018/08/05"
-	echo "          will compute  2017/03/17, 2017/03/16, 2018/08/05 and 2018/08/04"
+	echo "     Options:"
+	echo "	    -s \"STA1 STA2...\""
+	echo "            station code or station list with double quotes"
+	echo "	         default is all nodes associated with local WebObs $GRID"
+	echo "            or a list of nodes $NODES defined in .rc"
+	echo "       -d \"yyyy/mm/dd,yyyy/mm/dd\""
+	echo "            choose days to start process; the DAYS argument can still be used to"
+	echo "            process previous days from the selected ones, for instance:"
+	echo "            gnss_run_gipsyx CONF 1 -d 2017/03/17,2018/08/05"
+	echo "            will compute  2017/03/17, 2017/03/16, 2018/08/05 and 2018/08/04"
+	echo "       -final"
+	echo "            use only final orbit"
 	echo "       -force"
-	echo "          forces the process despite existence of final results"
+	echo "            forces the process despite existence of final results"
 	echo "       -lock"
-	echo "          creates a lock file to prevent multiple process of gnss_run_gipsyx"
+	echo "            creates a lock file to prevent multiple process of gnss_run_gipsyx"
 	echo ""
 	exit 0;
 fi
@@ -81,46 +83,52 @@ TODAY=$(date -u +"%Y/%m/%d")
 DAYS=$2
 DAYLIST=$(for d in $(seq $DAYS -1 0);do date -u -d "$d day ago" +"%Y/%m/%d";done)
 
+LOG=gd2e.log
+
 # boolean for forcing process (default value doesn't force)
 FORCE=0
 
-# Optionnal parameters
+echo "*** GipsyX / WebObs $GRID GNSS File Processing ***"
+
+# Optional parameters
 for (( i=1; i<=$#; i++)); do
-
-    case ${!i} in
-
-        -force) 
-        declare FORCE=1
-        echo "Force computation despites final orbits already exist";;
-
-        -s) 
-        j=$((i+1))
-        IFS=' ' read -ra arrayStation <<< "${!j}"
-        declare NODES=${arrayStation[@]};;
-
-	-d)
-        k=$((i+1))
-        IFS=',' read -ra arrayDay <<< "${!k}"
-        declare STARTDAYS=${arrayDay[@]}
-        DAYLIST= $()
-        for start in $STARTDAYS;do
-                declare L=$(for d in $(seq $DAYS -1 0);do date -d "$d day ago $start" +%Y/%m/%d;done)
-                DAYLIST=("${DAYLIST[@]}" "${L[@]}")     
-        done
-        DAYLIST=($(printf "%s\n" "${DAYLIST[@]}" | sort -u | tr '\n' ' '))
-        declare DAYLIST=${DAYLIST[@]} #converting to proper format
-        ;;
-
-	-lock)
-	# make sure the lockfile is removed when we exit and then claim it
-	trap "rm -f ${LOCKFILE}; exit" INT TERM EXIT
-	echo $$ > ${LOCKFILE}
-        
-        esac
+   case ${!i} in
+		-final)
+			ORBITS=( "flinn" )
+			echo "Will use only final orbit"
+		;;
+   	-force)
+      	declare FORCE=1
+      	echo "Force computation despites final orbits already exist"
+		;;
+   	-debug)
+      	declare DEBUG=1
+      	echo "Debug mode: temporary directories will NOT be deleted!"
+		;;
+   	-s)
+      	j=$((i+1))
+      	IFS=' ' read -ra arrayStation <<< "${!j}"
+      	declare NODES=${arrayStation[@]}
+		;;
+		-d)
+      	k=$((i+1))
+      	IFS=',' read -ra arrayDay <<< "${!k}"
+      	declare STARTDAYS=${arrayDay[@]}
+      	DAYLIST= $()
+      	for start in $STARTDAYS;do
+      		declare L=$(for d in $(seq $DAYS -1 0);do date -d "$d day ago $start" +%Y/%m/%d;done)
+         	DAYLIST=("${DAYLIST[@]}" "${L[@]}")
+      	done
+      	DAYLIST=($(printf "%s\n" "${DAYLIST[@]}" | sort -u | tr '\n' ' '))
+      	declare DAYLIST=${DAYLIST[@]} #converting to proper format
+      ;;
+		-lock)
+			# make sure the lockfile is removed when we exit and then claim it
+			trap "rm -f ${LOCKFILE}; exit" INT TERM EXIT
+			echo $$ > ${LOCKFILE}
+   esac
 done
 
-
-echo "*** GipsyX / WebObs $GRID GNSS File Processing ***"
 
 for station in $NODES; do
 	# cleans the string !
@@ -156,7 +164,7 @@ for station in $NODES; do
 		gipsyres="$res.tdp"
 		gipsylog="$res.log"
 
-		if [[ $FORCE == 0 && -s "$gipsyres" ]]; then 
+		if [[ $FORCE == 0 && -s "$gipsyres" ]]; then
 			echo "   file $gipsyres [flinn] already exists..."
 		else
 			# path of raw data: eval() will replace any variables in $FMT (from .rc)
@@ -171,11 +179,11 @@ for station in $NODES; do
 
 				# real-time case: makes a 24h window from yesterday+today data
 				if [[ "$REALTIME" == "Y" && "$ymd" == "$TODAY" ]]; then
-					
+
 					rinex1=$tmpdir/rinex1 # 2 days ago
 					rinex2=$tmpdir/rinex2 # yesterday
 					rinex3=$tmpdir/rinex3 # today
-					
+
 					declare ORBITS=( "ultra" ) #reaffect orbit value because only ultra can be used for realtime
 
 					yesterday=$(date -u -d "1 day ago" +"%Y/%m/%d")
@@ -183,35 +191,35 @@ for station in $NODES; do
 					echo "   Real-time case: Appending $two_days_ago, $yesterday and $TODAY to process 30h of data."
 
 					# converting yesterday rinex
-                                        doy=$(date -d "$yesterday" +"%j")
-                                        yyyy=${yesterday:0:4}
-                                        mm=${yesterday:5:2}
-                                        dd=${yesterday:8:2}
-                                        RAW2=$(eval "echo $FMT")
+               doy=$(date -d "$yesterday" +"%j")
+               yyyy=${yesterday:0:4}
+               mm=${yesterday:5:2}
+               dd=${yesterday:8:2}
+               RAW2=$(eval "echo $FMT")
 					echo "$RAW2"
 					$PROGDIR/raw2rinex "$RAW2" $rinex2 $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna
 					if [[ ! -z $VERBOSE || $? != 0 ]]; then
 						echo "$PROGDIR/raw2rinex \"$RAW2\" $rinex2 $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna"
 					fi
-					
+
 
 					#converting 2 days ago rinex
-		                        doy=$(date -d "$two_days_ago" +"%j")
-                                        yyyy=${two_days_ago:0:4}
-                                        mm=${two_days_ago:5:2}
-                                        dd=${two_days_ago:8:2}
-                                        RAW1=$(eval "echo $FMT")
+		         doy=$(date -d "$two_days_ago" +"%j")
+               yyyy=${two_days_ago:0:4}
+               mm=${two_days_ago:5:2}
+               dd=${two_days_ago:8:2}
+               RAW1=$(eval "echo $FMT")
 					echo "$RAW1"
-                                        $PROGDIR/raw2rinex "$RAW1" $rinex1 $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna
-                                        if [[ ! -z $VERBOSE || $? != 0 ]]; then
-                                                echo "$PROGDIR/raw2rinex \"$RAW1\" $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna"
-                                        fi
+               $PROGDIR/raw2rinex "$RAW1" $rinex1 $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna
+               if [[ ! -z $VERBOSE || $? != 0 ]]; then
+               	echo "$PROGDIR/raw2rinex \"$RAW1\" $TEQCOPTIONS -O.mn \"$FID\" -O.mo \"$FID\" $receiver $antenna"
+               fi
 
 					mv $rinex $rinex3 #already converted rinex for today
 					if [[ ! -z $VERBOSE || $? != 0 ]]; then
 						echo "   mv $rinex $rinex2"
-					fi                 
-                                        
+					fi
+
 					endwindow=$(date -u -d "$DATA_DELAY ago" +"%Y%m%d%H%M%S")
 					teqc -phc +quiet -e $endwindow -dh 30 $rinex1 $rinex2 $rinex3 > $rinex
 					if [[ ! -z $VERBOSE || $? != 0 ]]; then
@@ -223,8 +231,6 @@ for station in $NODES; do
 				tdp="$tmpdir/smoothFinal.tdp"
 				cd $tmpdir
 
-
-				
 				# makes a loop for different orbits precision: from Final to Ultra
 				for orbit in "${ORBITS[@]}" ; do
 					if [[ $orbit == "ql" && -s $gipsyres.$orbit && $FORCE == 0 ]]; then
@@ -235,30 +241,35 @@ for station in $NODES; do
 						if [ "$ORBITSDIR" != "" ]; then #running Gipsy from local orbit
 
 							case $orbit in
-	
 								flinn)
-								declare product="Final";;
+									declare product="Final";;
 								ql)
-								declare product="Rapid";;
+									declare product="Rapid";;
 								ultra)
-								declare product="Ultra";;
+									declare product="Ultra";;
 							esac
-							
+
 							# calling download_orbit
 							$PROGDIR/download_orbit 0 $ORBITSDIR -o $product -d $ymd $DOWNLOAD_OPTIONS
 
-							if [ ! -e "$ORBITSDIR/$product/$yyyy/$yyyy-$mm-$dd.eo.gz" ]; then
+							if [ -e "$ORBITSDIR/$product/$yyyy/$yyyy-$mm-$dd.eo.gz" ]; then
+								ORBITOK=1
+							else
+								ORBITOK=""
 								continue # if download not successfull go to next orbit
 							fi
-
-							cmd="gd2e.py -rnxFile $rinex -GNSSproducts $ORBITSDIR/$product $GIPSYOPTIONS > gd2e.log 2>&1"
+							ORBITOPT="$ORBITSDIR/$product"
 
 						else #running Gipsy from direct download
-							cmd="gd2e.py -rnxFile $rinex -GNSSproducts $orbit $GIPSYOPTIONS > gd2e.log 2>&1"
+							ORBITOPT=$orbit
 						fi
-
+						cmd="gd2e.py -rnxFile $rinex -GNSSproducts $ORBITOPT $GIPSYOPTIONS"
 						echo "$cmd"
-						eval $cmd
+						if [ -z DEBUG ]; then
+							eval "$cmd > $LOG 2>&1"
+						else
+							eval $cmd
+						fi
 						rc=$?
 						if [[ $rc == 0 && -s $tdp ]]; then
 							mkdir -p "$DEST/$FID/$year"
@@ -267,16 +278,26 @@ for station in $NODES; do
 							echo "==> $gipsyres [$orbit] written."
 							if [[ "$orbit" != "flinn" ]]; then
 								mv $gipsyres $gipsyres.$orbit
-							fi 
+							fi
 							break
 						else
 							echo "   $cmd"
-							echo "   ** WARNING: Problem to process gd2e... May be orbit $orbit not yet available?"
+							if [ -z $ORBITOK ]; then
+								echo "   ** WARNING: Problem to process gd2e... May be orbit $orbit not yet available?"
+							else
+								echo "   ** ERROR: Problem to process gd2e... Please check logs."
+								ERROR=1
+								break
+							fi
+
+
 						fi
 					fi
 				done
-				mv -f gd2e.log $gipsylog
-				gzip -f $gipsylog
+				if [ -z $ERROR ]; then
+					mv -f $LOG $gipsylog
+					gzip -f $gipsylog
+				fi
 			else
 				echo "   no data to process in $RAW."
 			fi
@@ -286,7 +307,7 @@ done
 
 echo "*************************************"
 
-if [ -z $DEBUG ]; then 
+if [ -z $DEBUG ]; then
 	rm -rf $tmpdir
 fi
 
