Improve systemd integration
This commit mainly change the behaviour of 'scheduler.pl' and 'postboard.pl'
and their helper shell scripts for an improved integration to systemd, along
with a new feature/fix that allows to bind the Scheduler control interface to
a specific network interface.

Full description of changes:

- 'scheduler.pl' and 'postboard.pl' no longer check or write the PID file, it
  should be done by the forking process (the shell scripts in our case) to
  ensure a good timing in the availability of the PID file.

- the helper scripts 'scheduler' and 'postboard' no longer refuse to start
  when a PID file exists and the process designated by the PID is not alive.
  For improved crash recovery, they now ignore and remove the PID file and
  normally process the provided command.

  This is more in line with systemd behaviour, as the former behaviour could
  confuse the administrator when using systemd: the service would crash at
  first start, but would immediately be successfully restarted by systemd
  (thanks to the Restart= configuration) because systemd automatically removes
  the PID file as part of the 'stop' step of the 'restart' process.

  The PID file is now also ignored and removed (with a comment in the logs)
  when the PID file designates a process that does not runs the expected
  script (in case the PID were re-used by another process).

- postboard.pl and scheduler.pl now exit with code 0 (success) when receiving
  the TERM signal so that systemd reports the daemon has exited cleanly.

- for improved reliability, the templates for the systemd services now default
  to directly sending the TERM signal to stop the postboard or the scheduler,
  instead of using a script in ExecStop= that sends the same signal.

- the systemd service woscheduler.service now makes sure wopostboard.service
  is started before it starts itself (to be able to send notifications).

- a new command 'terminate' was added to the 'scheduler' and 'postboard'
  scripts that sends the daemon a TERM signal to exit cleanly with exit code 0
  (without waiting for children processes in the case of the scheduler). This
  is a better alternative to the 'kill' command that should only be used as a
  last resort (or not at all).

- updated the 'scheduler' script to use the newer 'ss' command on systems that
  miss the 'netstat' command (which is not installed by default on latest
  GNU/Linux systems). Fixes #63.

- added scheduler configuration option LISTEN_ADDR to bind the UDP control
  socket to a specific interface (this allows to easily limit access to the
  local machine, as the control protocol does not have any authentication
  system). Fixes #62.

- scheduler.pl now issues a notification when it starts, just like it does
  when it stops. Administrators are thus informed that the scheduler has
  restarted after being stopped.

- the scheduler 'killjob' request now reports when the argument is invalid (it
  should be of the form kid=XXX) or if the job could not be sent the TERM
  signal.

- substituted many system commands run by qx() by native perl functions in
  scheduler.pl and postboard.pl.

- the helper scripts 'scheduler' and 'postboard' now use more explicit
  variables names and factorise verification code using 'case' features to
  improve code maintainability.

- removed some trailing whitespaces.

diff --git a/CODE/shells/postboard b/CODE/shells/postboard
--- a/CODE/shells/postboard
+++ b/CODE/shells/postboard
@@ -1,75 +1,124 @@
 #!/bin/bash
+#
+# Helper script to start, stop, and get the status of the WebObs Postboard.
+#
 
-woconf() {
-	# internal: (re)-loads WEBOBS.rc as the set of bash variables WO__*
-	unset $(/usr/bin/env | egrep '^WO__' | /usr/bin/cut -d= -f1)
-	oIFS=${IFS}; IFS=$'\n'
-	LEXP=($(perl /etc/webobs.d/../CODE/cgi-bin/exposerc.pl '=' 'WO__'))
-	for i in $(seq 0 1 $(( ${#LEXP[@]}-1 )) ); do export ${LEXP[$i]}; done
-	IFS=${oIFS}
-}
+# How many time to wait for the process to exit after sending it the TERM
+# signal (see man timeout(1) for details).
+WAIT_TIMEOUT=20s
 
-woconf;
-savedpid=$(cat ${WO__ROOT_LOGS}/postboard.pid 2>/dev/null)
-savedpid=${savedpid:=0}
+# Load configuration from WEBOBS.rc as WO__* environment variables
+. /etc/webobs.d/../CODE/shells/readconf
+
+
+DAEMON_SCRIPT=postboard.pl
+PID_FILE="${WO__ROOT_LOGS}/${DAEMON_SCRIPT%%.*}.pid"
+
+savedpid=$(cat $PID_FILE 2>/dev/null)
+if [[ -n $savedpid ]] && kill -0 $savedpid 2> /dev/null; then
+	# A PID was saved and the corresponding process exists
+	if ps -o cmd --no-headers -p $savedpid | grep -q "\b$DAEMON_SCRIPT\b"; then
+		running=1
+	else
+		rm -f "$PID_FILE"
+		echo "Warning: PID file references PID $savedpid" \
+			"but this process does not seem to be running" \
+			"'$DAEMON_SCRIPT' and was deleted."
+		running=0
+	fi
+else
+	# PID file is missing or the referenced process is not alive (or not ours)
+	# Delete any stale PID file to ensure the daemon can start.
+	rm -f "$PID_FILE"
+	running=0
+fi
 
 case "$1" in
-	start)
-		if [[ $savedpid -ne 0 ]]; then 
-			echo "marked as already started, pid $savedpid"
-		else
-			cd /etc/webobs.d/../CODE/cgi-bin
-			if [ -n "${WO__POSTBOARD_ERROR_FILE}" ]; then
-				# Don't use eval as it would fork a new process not monitored by systemd
-				perl postboard.pl $WO__POSTBOARD_CMD_OPTS 2> $WO__POSTBOARD_ERROR_FILE &
-			else
-				perl postboard.pl $WO__POSTBOARD_CMD_OPTS &
-			fi
-			echo
-		fi
-		;;
-	stop)
-		if [[ $savedpid -ne 0 ]]; then
-			kill -s SIGTERM $savedpid 
-		fi
-		;;
-	status)
-		if [[ $savedpid -ne 0 ]]; then
-			statusts=$(date +'%F %T (%z)')
-			statusps=($(ps -o user,start_time,cmd --no-headers -p $savedpid))
-			if [[ ${#statusps[@]} > 0 ]]; then
-				echo "STATTIME=${statusts}"
-				echo "STARTED=${statusps[1]}"
-				echo "PID=${savedpid}"
-				echo "USER=${statusps[0]}"
-				# ATT: may get Permission denied on /proc/<pid>
-				# so can't really tell wether fifo and log are opened
-				statusfifo=($(lsof -p $savedpid | grep FIFO))
-				if [[ ${#statusfifo[@]} > 0 ]]; then
-					echo "FIFO=${statusfifo[8]}"
-				fi
-				statuslog=($(lsof -p $savedpid | grep "${WO__ROOT_LOGS}/postboard.log"))
-				if [[ ${#statuslog[@]} > 0 ]]; then
-					echo "LOG=${statuslog[8]}" 
-				fi
-			else 
-				echo "POSTBOARD NOT RUNNING but has saved pid=$savedpid"
-			fi
-		fi
-		;;
-	kill)
-		if [[ $savedpid -ne 0 ]]; then
-			kill -9 $savedpid
-			rm -f ${WO__ROOT_LOGS}/postboard.pid >/dev/null 2>&1
-		fi
-		;;
-	notify)
-		echo "msg=" $2
-		;;
-	*)
-		echo "Usage: $0 {start|stop|status|kill}"
-		exit 1
-esac
 
-exit 0
+	start)
+		if [[ $running -eq 1 ]]; then
+			echo "Postboard already started, pid $savedpid"
+			exit 1
+		fi
+		cd /etc/webobs.d/../CODE/cgi-bin
+		if [ -n "${WO__POSTBOARD_ERROR_FILE}" ]; then
+			perl $DAEMON_SCRIPT $WO__POSTBOARD_CMD_OPTS 2> $WO__POSTBOARD_ERROR_FILE &
+			bg_pid=$!
+		else
+			perl $DAEMON_SCRIPT $WO__POSTBOARD_CMD_OPTS &
+			bg_pid=$!
+		fi
+		# Make the pid file available before exiting (required for systemd support)
+		echo $bg_pid > $PID_FILE
+		;;
+
+	stop|terminate|kill)
+		# Exit with 0 if not running
+		# (this allows the command to be used by systemd as 'ExecStop=')
+		if [[ $running -ne 1 ]]; then
+			echo "Scheduler is stopped."
+			exit 0
+		fi
+		;;&  # continue testing other patterns
+
+	stop|terminate)
+		echo "shutdown requested: sending SIGTERM to pid $savedpid."
+		if kill -s SIGTERM $savedpid; then
+			timeout $WAIT_TIMEOUT sh -c "while kill -0 $savedpid 2> /dev/null; do sleep 1; done"
+			rc=$?
+			if [[ $rc -eq 1 ]]; then
+				echo "Postboard has exited."
+			elif [[ $rc -eq 124 ]]; then
+				echo "warning: postboard has not exited after $WAIT_TIMEOUT."
+			else
+				echo "error while waiting for the postboard to exit."
+			fi
+		else
+			echo "error sending signal to $savedpid: unable to stop the postboard."
+		fi
+		;;
+
+	kill)
+		kill -9 $savedpid
+		rm -f $PID_FILE
+		;;
+
+	status)
+		if [[ $running -eq 0 ]]; then
+			echo "Error: could not read the process id. Is the postboard running?"
+			exit 1
+		fi
+		statusts=$(env LANG=C date +'%c (%z)')  # match ps lstart time format for clarity
+		read ps_user ps_starttime <<< $(ps -o user,lstart --no-headers -p $savedpid)
+		if [[ -n $ps_starttime ]]; then
+			echo "STATTIME=$statusts"
+			echo "STARTED=$ps_starttime"
+			echo "PID=$savedpid"
+			echo "USER=$ps_user"
+			# ATT: may get Permission denied on /proc/<pid>
+			# so can't really tell wether fifo and log are opened
+			statusfifo=($(lsof -p $savedpid | grep FIFO))
+			if [[ ${#statusfifo[@]} > 0 ]]; then
+				echo "FIFO=${statusfifo[8]}"
+			fi
+			statuslog=($(lsof -p $savedpid | grep "${WO__ROOT_LOGS}/postboard.log"))
+			if [[ ${#statuslog[@]} > 0 ]]; then
+				echo "LOG=${statuslog[8]}"
+			fi
+		else
+			echo "Error: could not read process information for saved process id $savedpid"
+			exit 1
+		fi
+		;;
+
+	*)
+		echo "Usage: $0 {start|stop|terminate|kill|status}"
+		echo "       start          start, if not already active"
+		echo "       stop           request postboard exit stop"
+		echo "       terminate      same as 'stop'"
+		echo "       kill           force immediate exit, really not recommended"
+		echo "       status         display status/indicators/settings"
+		exit 1
+        ;;
+esac
 
