Improve systemd integration
This commit mainly change the behaviour of 'scheduler.pl' and 'postboard.pl'
and their helper shell scripts for an improved integration to systemd, along
with a new feature/fix that allows to bind the Scheduler control interface to
a specific network interface.

Full description of changes:

- 'scheduler.pl' and 'postboard.pl' no longer check or write the PID file, it
  should be done by the forking process (the shell scripts in our case) to
  ensure a good timing in the availability of the PID file.

- the helper scripts 'scheduler' and 'postboard' no longer refuse to start
  when a PID file exists and the process designated by the PID is not alive.
  For improved crash recovery, they now ignore and remove the PID file and
  normally process the provided command.

  This is more in line with systemd behaviour, as the former behaviour could
  confuse the administrator when using systemd: the service would crash at
  first start, but would immediately be successfully restarted by systemd
  (thanks to the Restart= configuration) because systemd automatically removes
  the PID file as part of the 'stop' step of the 'restart' process.

  The PID file is now also ignored and removed (with a comment in the logs)
  when the PID file designates a process that does not runs the expected
  script (in case the PID were re-used by another process).

- postboard.pl and scheduler.pl now exit with code 0 (success) when receiving
  the TERM signal so that systemd reports the daemon has exited cleanly.

- for improved reliability, the templates for the systemd services now default
  to directly sending the TERM signal to stop the postboard or the scheduler,
  instead of using a script in ExecStop= that sends the same signal.

- the systemd service woscheduler.service now makes sure wopostboard.service
  is started before it starts itself (to be able to send notifications).

- a new command 'terminate' was added to the 'scheduler' and 'postboard'
  scripts that sends the daemon a TERM signal to exit cleanly with exit code 0
  (without waiting for children processes in the case of the scheduler). This
  is a better alternative to the 'kill' command that should only be used as a
  last resort (or not at all).

- updated the 'scheduler' script to use the newer 'ss' command on systems that
  miss the 'netstat' command (which is not installed by default on latest
  GNU/Linux systems). Fixes #63.

- added scheduler configuration option LISTEN_ADDR to bind the UDP control
  socket to a specific interface (this allows to easily limit access to the
  local machine, as the control protocol does not have any authentication
  system). Fixes #62.

- scheduler.pl now issues a notification when it starts, just like it does
  when it stops. Administrators are thus informed that the scheduler has
  restarted after being stopped.

- the scheduler 'killjob' request now reports when the argument is invalid (it
  should be of the form kid=XXX) or if the job could not be sent the TERM
  signal.

- substituted many system commands run by qx() by native perl functions in
  scheduler.pl and postboard.pl.

- the helper scripts 'scheduler' and 'postboard' now use more explicit
  variables names and factorise verification code using 'case' features to
  improve code maintainability.

- removed some trailing whitespaces.

diff --git a/CODE/shells/scheduler b/CODE/shells/scheduler
--- a/CODE/shells/scheduler
+++ b/CODE/shells/scheduler
@@ -1,150 +1,194 @@
 #!/bin/bash
+#
+# Helper script to start, stop, and interact with the WebObs Scheduler.
+#
 
-woconf() {
-	# internal: (re)-loads WEBOBS.rc as the set of bash variables WO__*
-	# + (re)-loads WO_CONF_SCHEDULER as bash variabls SC__* 
-	unset $(/usr/bin/env | egrep '^WO__' | /usr/bin/cut -d= -f1)
-	oIFS=${IFS}; IFS=$'\n'
-	LEXP=($(perl /etc/webobs.d/../CODE/cgi-bin/exposerc.pl '=' 'WO__'))
-	for i in $(seq 0 1 $(( ${#LEXP[@]}-1 )) ); do export ${LEXP[$i]}; done
-	LEXP=($(perl /etc/webobs.d/../CODE/cgi-bin/exposerc.pl '=' 'SC__' 'CONF_SCHEDULER'))
-	for i in $(seq 0 1 $(( ${#LEXP[@]}-1 )) ); do export ${LEXP[$i]}; done
-	IFS=${oIFS}
-}
+# How many time to wait for the process to exit after sending it the TERM
+# signal (see man timeout(1) for details).
+WAIT_TIMEOUT=20s
 
-woconf;
-savedpid=0; running=0; cantalk2=0;
-savedpid=$(cat ${WO__ROOT_LOGS}/scheduler.pid 2>/dev/null)
-if [[ ${savedpid} -ne 0 && $(ps -p${savedpid} -opid --no-headers) -eq ${savedpid} ]]; then running=1; fi
-listening=$(netstat -uln | grep -c "${SC__PORT}" 2>/dev/null)
-if [[ ${running} -eq 1 && ${listening} -eq 1 ]]; then cantalk2=1; fi
 
-#schedudp="/dev/udp/127.0.0.1/${SC__PORT}"
-holdon="Please wait..."
+# Load the 'woconf' function
+. /etc/webobs.d/../CODE/shells/wolib.bash
+# Load configuration from WEBOBS.rc as WO__* environment variables.
+woconf 'WO__'
+# Load configuration from file $WEBOBS{CONF_SCHEDULER} as SC__* environment
+# variables.
+woconf 'SC__' 'CONF_SCHEDULER'
+
+
+DAEMON_SCRIPT=scheduler.pl
+PID_FILE="${WO__ROOT_LOGS}/${DAEMON_SCRIPT%%.*}.pid"
+
+savedpid=$(cat $PID_FILE 2>/dev/null)
+if [[ -n $savedpid ]] && kill -0 $savedpid 2> /dev/null; then
+	# A PID was saved and the corresponding process exists
+	if ps -o cmd --no-headers -p $savedpid | grep -q "\b$DAEMON_SCRIPT\b"; then
+		running=1
+	else
+		rm -f "$PID_FILE"
+		echo "Warning: PID file references PID $savedpid" \
+			"but this process does not seem to be running" \
+			"'$DAEMON_SCRIPT' and was deleted."
+		running=0
+	fi
+else
+	# PID file is missing or the referenced process is not alive (or not ours)
+	# Delete any stale PID file to ensure the daemon can start.
+	rm -f "$PID_FILE"
+	running=0
+fi
+
+holdon="Connecting to scheduler..."
 
 case "$1" in
+
 	start)
-		if [[ ${running} -eq 1 ]]; then echo "scheduler already started, pid $savedpid"; exit 1; fi
-		if [[ ${savedpid} -ne 0 && ${running} -eq 0 ]]; then echo "won't start: scheduler.pid says $savedpid and $savedpid not running"; exit 1; fi
+		if [[ $running -eq 1 ]]; then
+			echo "Scheduler already running with PID $savedpid"
+			exit 1
+		fi
 		cd /etc/webobs.d/../CODE/cgi-bin
 		if [ -n "${SC__ERROR_FILE}" ]; then
-			# Don't use eval as it will fork a new process not monitored by systemd
-			perl scheduler.pl $SC__CMD_OPTS 2> $SC__ERROR_FILE &
+			perl $DAEMON_SCRIPT $SC__CMD_OPTS 2> $SC__ERROR_FILE &
+			bg_pid=$!
 		else
-			perl scheduler.pl $SC__CMD_OPTS &
+			perl $DAEMON_SCRIPT $SC__CMD_OPTS &
+			bg_pid=$!
 		fi
-		echo
+		# Make the pid file available before exiting (required for systemd support)
+		echo $bg_pid > "$PID_FILE"
 		;;
+
+	stop|terminate|kill)
+		# Exit with 0 if not running
+		# (this allows the command to be used by systemd as 'ExecStop=')
+		if [[ $running -ne 1 ]]; then
+			echo "Scheduler is stopped."
+			exit 0
+		fi
+		;;&  # continue testing other patterns
+
+	status|ps|qs|runq|jobq|verbose|quiet|stop|pause|resume|flog|submit|killjob|enq|deq)
+		if [[ $running -ne 1 ]]; then
+			echo "Error: scheduler is not running."
+			exit 1;
+		fi
+		listening=$({ netstat -uln 2> /dev/null || ss -uln; } | grep -c ":${SC__PORT}\b" 2>/dev/null)
+		if [[ ${listening} -ne 1 ]]; then
+			echo "Error: scheduler is not listening on UDP port ${SC__PORT}."
+			exit 1;
+		fi
+		;;&  # Continue testing other patterns
+
 	status)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			#oIFS=${IFS}; IFS=$'\n'; exec 3<>${schedudp}; echo ${holdon}; echo "cmd stat" >&3; rarr=$(timeout 3 cat <&3); echo "${rarr}"; IFS=${oIFS} 
-			#exec 3>&-
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd stat"'
-		#else
-		#	echo "scheduler not running or not listening"
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd stat"'
 		;;
+
 	ps)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			ps -p ${savedpid} -osid --no-headers | xargs ps -H -o pid,pgrp,etime,pcpu,pmem,vsize,cmd -s
-		fi
+		ps -p $savedpid -osid --no-headers | xargs ps -H -o pid,pgrp,etime,pcpu,pmem,vsize,cmd -s
 		;;
+
 	qs)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd qs"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd qs"'
 		;;
+
 	runq)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd runq"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd runq"'
 		;;
+
 	jobq)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd jobq"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd jobq"'
 		;;
+
 	verbose)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd verbose"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd verbose"'
 		;;
+
 	quiet)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd quiet"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd quiet"'
 		;;
+
 	stop)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd stop"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd stop"'
 		;;
+
 	pause)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd pause"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd pause"'
 		;;
+
 	resume)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd resume"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd resume"'
 		;;
+
 	flog)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd flog"'
-		fi
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl 'msg=>"cmd flog"'
 		;;
-	kill)
-		if [[ $savedpid -ne 0 ]]; then
-			kill -9 $savedpid
-			rm -f ${WO__ROOT_LOGS}/scheduler.pid >/dev/null 2>&1
-		fi
-		;;
+
 	submit)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			shift
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"job $@\""
-		fi
+		shift
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"job $@\""
 		;;
+
 	killjob)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			shift
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"killjob $@\""
-		fi
+		shift
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"killjob $@\""
 		;;
+
 	enq)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			shift
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"enq $@\""
-		fi
+		shift
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"enq $@\""
 		;;
+
 	deq)
-		if [[ ${cantalk2} -eq 1 ]]; then
-			shift
-			echo $holdon
-			perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"deq $@\""
+		shift
+		echo $holdon
+		perl /etc/webobs.d/../CODE/cgi-bin/wsudp.pl "msg=>\"deq $@\""
+		;;
+
+	kill)
+		kill -9 $savedpid
+		rm -f "$PID_FILE"
+		;;
+
+	terminate)
+		echo "shutdown requested: sending SIGTERM to pid $savedpid."
+		if kill -TERM $savedpid; then
+			timeout $WAIT_TIMEOUT sh -c "while kill -0 $savedpid 2> /dev/null; do sleep 1; done"
+			rc=$?
+			if [[ $rc -eq 1 ]]; then
+				echo "Scheduler has exited."
+			elif [[ $rc -eq 124 ]]; then
+				echo "warning: scheduler has not exited after $WAIT_TIMEOUT."
+			else
+				echo "error while waiting for the scheduler to exit."
+			fi
+		else
+			echo "error sending signal to $savedpid: unable to stop the scheduler."
 		fi
 		;;
+
 	*)
-		echo "Usage: $0 {enq|deq|flog|jobq|kill|pause|ps|qs|quiet|resume|runq|start|status|stop|submit|killjob|verbose}"
+		echo "Usage: $0 {enq|deq|flog|jobq|terminate|kill|pause|ps|qs|quiet|resume|runq|start|status|stop|submit|killjob|verbose}"
 		echo "       start          start, if not already active"
-		echo "       stop           stop, waiting for active kids to end"
+		echo "       stop           stop, $DAEMON_SCRIPT will wait for active kids to end"
 		echo "       pause          hold execution (suspend jobs processing)"
 		echo "       resume         resume execution"
-		echo "       kill           forced stop, not recommended"
+		echo "       terminate      request immediate exit without stopping kids"
+		echo "       kill           force immediate exit, really not recommended"
 		echo "       verbose        log verbosity"
 		echo "       quiet          log verbosity"
 		echo "       status         display status/indicators/settings"
@@ -163,6 +207,4 @@ case "$1" in
 		echo "                      job outputs and temporary files might remain and must be checked.\n"
 		exit 1
 esac
-
-exit 0
 
