further advances in migration

diff --git a/SETUP/migration/form2genform b/SETUP/migration/form2genform
--- a/SETUP/migration/form2genform
+++ b/SETUP/migration/form2genform
@@ -1,9 +1,10 @@
 #!/bin/bash
-# migration of existing former FORM (.DAT text file based) to GENFORM (.db based)
+# Ojective: migration of existing former FORM (.DAT text file based) to GENFORM (.db based)
+# and the new grid FORM structure
 #
 # Author: François Beauducel
 # Created: 2024-04-21
-# Updated: 2024-12-18
+# Updated: 2024-12-26
 
 
 if [ -z "$1" ]; then
@@ -24,40 +25,48 @@ WOROOT=$1
 DBF=$WOROOT/DATA/DB/WEBOBSFORMS.db
 TMP=/tmp/webobs_genform_migration
 
+
+P=`dirname $0`
+if ! [[ -e $P/../dutils.sh ]]; then
+	echo 'Missing dutils.sh. Bye.'
+	exit 64
+fi
+. $P/../dutils.sh
+
+
+
 # =============================================================================
 # === EAUX --> modèle WATERS_fr
 
 DBT=eaux
-DAT=$1/DATA/DB/OVSG/EAUX.DAT
+DAT=$1/DATA/DB/OVSG/EAUX.DAT 
 NBI=24
 
-echo  -n "Creating/populating $DBT table ..."
+echo  -n "Creating/populating $DBT table with former $DAT ($NBI inputs)..."
 
 echo "BEGIN TRANSACTION;" > $TMP
 echo "DROP TABLE if exists $DBT;" >> $TMP
 printf "CREATE TABLE $DBT (id integer PRIMARY KEY AUTOINCREMENT, trash boolean DEFAULT FALSE, quality integer, node text NOT NULL" >> $TMP
 printf ", edate datetime, edate_min datetime, sdate datetime NOT NULL, sdate_min datetime, operators text NOT NULL" >> $TMP
 printf ", comment text, tsupd text NOT NULL, userupd text NOT NULL" >> $TMP
-for i in {1..$NBI}
-	do printf ", input%02d text" >> $TMP;
-done
+for i in $(seq 1 $NBI); do printf ", input%02d text" $i >> $TMP; done
 echo ");" >> $TMP
 tac $DAT | iconv -f ISO-8859-1 -t UTF-8 | gawk -F'|' -v t="$DBT" -v n="$NBI" ' { if ($1 != "ID") { \
 	bin = ($1<0) ? 1:0; \
-	printf "INSERT INTO "t"(trash,node,edate,edate_min,sdate,sdate_min,operators"; \
-	for (i=1;i<=n;i++) printf ",input%02d",$i; \
-	printf ",comment,tsupd,userupd) ";\
+	printf "INSERT INTO "t"(trash,node,edate,edate_min,sdate,sdate_min,operators,comment,tsupd,userupd"; \
+	for (i=1;i<=n;i++) printf ",input%02d",i; \
+	printf ") ";\
 	printf "VALUES(\""bin"\",\""$4"\",\""$2" "$3"\",\""$2" "$3"\",\"\",\"\",\"!\""; \
-	for (i=5;i<28;i++) printf ",\""$i"\""; \
 	gsub(/"/,"\"\"", $28); \
 	gsub(/\045/,"\045\045", $28); \
 	printf ",\""$28" "$29"\""; \
 	if ($29 ~ /^\[.*\] /) {
-		n = split($29,vv,/\] \[/);
+		nn = split($29,vv,/\] \[/);
 		split(vv[1],v," ");
 		gsub(/\]/, "", v[2]); \
 		printf ",\""v[1]"\",\""v[2]"\"" \
 	} else { printf ",\"\",\"\"" }; \
+	for (i=5;i<n+5;i++) printf ",\""$i"\""; \
 	print ");" }}' >> $TMP 
 echo "COMMIT;" >> $TMP
 
