Add support for sqlite3 < 3.16.0 in database schema comparison
The 'cmpsql' script now also works with sqlite3 version < 3.16.0.
(This script is used by 'setup' to compare the schemas of an existing
and a temporary new sqlite3 database and warns the admin about any
discrepancy.)

diff --git a/SETUP/cmpsql b/SETUP/cmpsql
--- a/SETUP/cmpsql
+++ b/SETUP/cmpsql
@@ -11,14 +11,17 @@ fi
 
 normalize_schema() {
 	local dbfile="$1"
-	for f in $(sqlite3 $dbfile "select name from sqlite_master where type='table' and name!='sqlite_sequence' order by name")
+	for table in $(sqlite3 $dbfile "select name from sqlite_master where type='table' and name!='sqlite_sequence' order by name")
 	do
 		# Print table info
-		sqlite3 $dbfile "select '$f', ti.name, ti.type, ti.\"notnull\", ti.dflt_value, ti.pk from pragma_table_info('$f') as ti"
+		# Note: table-valued functions for PRAGMA feature is only available for SQLite version >= 3.16.0 (2017-01-02).
+		#sqlite3 $dbfile "select '$table', ti.name, ti.type, ti.\"notnull\", ti.dflt_value, ti.pk from pragma_table_info('$table') as ti"
+		sqlite3 $dbfile "PRAGMA table_info('$table')" | awk -v t="$table" 'BEGIN { FS=OFS="|" } { $1=t; print $0 } '
 		# Print index info
-		sqlite3 $dbfile "select '$f', ii.name, ii.\"unique\", ii.origin, ii.partial from pragma_index_list('users') as ii"
+		#sqlite3 $dbfile "select '$table', ii.name, ii.\"unique\", ii.origin, ii.partial from pragma_index_list('$table') as ii"
+		sqlite3 $dbfile "PRAGMA index_list('$table')" | awk -v t="$table" 'BEGIN { FS=OFS="|" } { $1=t; print $0 } '
 		# Print triggers
-		sqlite3 $dbfile "select '$f', type, rootpage, sql from sqlite_master where type='trigger' and tbl_name='$f'"
+		sqlite3 $dbfile "select '$table', type, rootpage, sql from sqlite_master where type='trigger' and tbl_name='$table'"
 	done
 }
 
@@ -26,11 +29,15 @@ if [[ -f $1 && -f $2 ]]; then
 	diffopt="-y --expand-tabs --suppress-common-lines"
 	normalize_schema $1 > cmpsql.s1
 	normalize_schema $2 > cmpsql.s2
+	if ! [[ -s cmpsql.s1 && -s cmpsql.s2 ]]; then
+		echo "$(basename $0): ERROR: unable to read database table schema, cannot compare databases."
+		exit 1
+	fi
 	difflst=$(diff $diffopt cmpsql.s1 cmpsql.s2)
 	if [[ ${#difflst} -gt 0 ]]; then
 		echo "WARNING: Found different schemas in $1 and $2"
 		echo "Please investigate visually"
-        echo "(Hint: this is the output of 'sqlite3 <dbfile> .schema')"
+		echo "(Hint: this is the output of 'sqlite3 <dbfile> .schema')"
 		echo -e "\n--- Schema for $1:"
 		sqlite3 $1 '.schema' | grep -v 'TABLE sqlite_sequence'
 		echo -e "\n--- Schema for $2:"
@@ -40,6 +47,6 @@ if [[ -f $1 && -f $2 ]]; then
 		echo "Success: found identical schemas in $1 and $2"
 	fi
 else
-	echo "`basename $0` couldn't find db(s)" ; 
+	echo "$(basename $0): ERROR: could not find database files, cannot compare databases $1 and $2." ;
 	exit 1;
 fi
